TAURI_API_ROOT := "src-tauri/.tauri"

TAURI_ANDROID_BUNDLE := "src-tauri/gen/android"

# Android
android-init:
    pnpm run tauri android init

android-dev:
    pnpm run tauri android dev

android-build:
    pnpm run tauri android build

android-release:
    ./android_release.sh

# iOS
ios-init:
    pnpm run tauri ios init

ios-dev:
    pnpm run tauri ios dev

ios-build:
    pnpm run tauri ios build

ios-build-universal:
    pnpm run tauri build -- --target universal-apple-darwin

ios-release:
    ./ios_release.sh

#ios-plugin:
#    cargo tauri plugin ios add --name {{name}}