TAURI_BUILD_ROOT := "src-tauri/gen"
TAURI_API_ROOT := "src-tauri/.tauri"
TAURI_RUST_TARGET := "./target"

ios-dev:
    pnpm run tauri ios dev
ios-renew:
    if [ -d {{TAURI_BUILD_ROOT}} ]; then \
        rm -r {{TAURI_BUILD_ROOT}}; \
    fi
    if [ -d {{TAURI_API_ROOT}} ]; then \
        rm -r {{TAURI_API_ROOT}}; \
    fi
    if [ -d {{TAURI_RUST_TARGET}} ]; then \
        sudo rm -rf {{TAURI_RUST_TARGET}}; \
    fi
    pnpm run tauri ios init

#ios-plugin:
#    cargo tauri plugin ios add --name {{name}}