TAURI_BUILD_ROOT := "src-tauri/gen"
TAURI_API_ROOT := "src-tauri/.tauri"

ios-dev:
    npm run tauri ios dev
ios-renew:
    if [ -d {{TAURI_BUILD_ROOT}} ]; then \
        rm -r {{TAURI_BUILD_ROOT}}; \
    fi
    if [ -d {{TAURI_API_ROOT}} ]; then \
        rm -r {{TAURI_API_ROOT}}; \
    fi
    npm run tauri ios init
    echo "(ios-renew) target/ may require removal"
#ios-plugin:
#    cargo tauri plugin ios add --name {{name}}